server.port=8081

spring.application.name=baseball-api

# 1. DB 접속 정보
# localhost 대신 host.docker.internal을 사용하여 윈도우의 MySQL에 접속할 수 있도록
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/baseball_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=3535

# 2. JPA/Hibernate 설정 (자동 테이블 생성)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true